### ISSUE TITLE
Back-Target

### ISSUE THREAD

**Issue by merglml** [Ilias-fmi/iliasVO#4]
bei Tab Link und Tab Tutor auf Exercise verweisen

**Comment by PhilippGruber** [comment]
Tab Link funktioniert obwohl er komischerweise nicht auf Übersicht sondern auf Info verweist. Trotzdem noch annehmbar. Bei Tab Tutor wirft er jetzt zwar keinen Fehler mehr, doch auf das Magazin zu verweisen ist noch nicht gut genug. Dieses Problem müsste man noch lösen.

**Comment by merglml** [comment]
funktionieren alle
